name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Bitcoin Core version"
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: xjonathanlei/bitcoind

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }} --build-arg "BITCOIN_CORE_VERSION=${{ github.event.inputs.version }}" -f ./Dockerfile .

      - name: Push Docker Image
        run: |
          docker tag ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }} ${DOCKER_REPOSITORY}:latest
          docker push ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}
          docker push ${DOCKER_REPOSITORY}:latest
